version: '3'
services:
    redis:
        image: redis
        restart: always
    service:
        image: node:10
        working_dir: /app/
        command: npm start
        volumes:
            - /c/projetos/TesteDockerKubernates/services:/app
        depends_on:
            - redis

    api:
        image: node:10
        working_dir: /app/
        command: npm start
        volumes:
            - /c/projetos/TesteDockerKubernates/api:/app
        depends_on:
            - redis
        ports:
            - 3001:3001
